<?php if (!empty($migrationPending)): ?>
<div class="alert alert-warning">Execute as migrações <strong>migration_workspace.sql</strong>, <strong>migration_workspace_v2.sql</strong>, <strong>migration_workspace_v3.sql</strong>, <strong>migration_workspace_v4.sql</strong>, <strong>migration_workspace_v5.sql</strong> e <strong>migration_automation_v2.sql</strong>.</div>
<?php endif; ?>

<?php if ($mode === 'calendar' && empty($migrationPending)): ?>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.19/index.global.min.css">
<div class="tc-workspace-toolbar">
  <div><h5>Calendário da equipe</h5><small>Arraste para reagendar, redimensione a duração e atribua eventos aos colaboradores.</small></div>
  <button class="btn btn-tc-primary" id="tcNewEvent"><i class="fa-solid fa-plus"></i> Novo evento</button>
</div>
<div class="tc-card"><div class="tc-card-body">
  <div id="tcFullCalendar" data-events="<?= e(url('calendario/eventos')) ?>" data-save="<?= e(url('calendario/eventos')) ?>" data-move="<?= e(url('calendario/eventos')) ?>" data-lead-search="<?= e(url('leads/buscar-rapido')) ?>" data-csrf="<?= e(Csrf::token()) ?>">
    <?php foreach ($users as $u): ?><span class="d-none tc-calendar-user" data-id="<?= (int)$u['id'] ?>" data-name="<?= e($u['name']) ?>"></span><?php endforeach; ?>
  </div>
</div></div>
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.19/index.global.min.js"></script>
<script src="<?= e(asset('js/calendar.js')) ?>"></script>

<?php elseif ($mode === 'content'): ?>
<link href="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.snow.css" rel="stylesheet">
<div class="tc-workspace-toolbar">
  <div><h5>Central de conhecimento</h5><small>Documentos, treinamentos, scripts, objeções, políticas e arquivos.</small></div>
  <div><button class="btn btn-outline-secondary tc-content-new" data-type="wiki">Nova Wiki</button> <button class="btn btn-tc-primary tc-content-new" data-type="documento">Novo documento</button></div>
</div>
<?php if(Auth::hasRole(['admin'])): ?>
<section class="tc-knowledge-crawler mb-3" id="tcKnowledgeCrawler" data-base="<?= e(url('conteudo/fontes')) ?>" data-csrf="<?= e(Csrf::token()) ?>">
  <div class="tc-knowledge-crawler-head"><div class="tc-crawler-icon"><i class="fa-solid fa-spider"></i></div><div><small>EXCLUSIVO DO ADMINISTRADOR</small><h6>Crawler da base de conhecimento</h6><p>Analise páginas públicas, revise o conteúdo e publique na Wiki para alimentar a IA.</p></div></div>
  <form id="tcKnowledgeSourceForm" class="tc-crawler-form"><div class="tc-crawler-primary"><div class="tc-crawler-url-wrap"><i class="fa-solid fa-link"></i><input type="url" class="form-control tc-crawler-url" name="url" required placeholder="Cole o link da página que deseja analisar"></div><button type="button" class="btn btn-outline-secondary" data-bs-toggle="collapse" data-bs-target="#tcCrawlerOptions"><i class="fa-solid fa-sliders"></i> Opções</button><button class="btn btn-tc-primary"><i class="fa-solid fa-plus"></i> Adicionar fonte</button></div><div class="collapse" id="tcCrawlerOptions"><div class="tc-crawler-options"><label><span>Categoria da Wiki</span><input class="form-control" name="category" value="Site oficial"></label><label><span>Tags para organização</span><input class="form-control" name="tags" value="site, crawler, titanium"></label><label class="tc-crawler-ai"><input class="form-check-input" type="checkbox" name="ai_enabled" value="1" checked><span><strong>Alimentar a IA</strong><small>Disponibilizar somente depois da publicação</small></span></label></div></div></form>
  <div class="tc-crawler-security"><i class="fa-solid fa-shield-halved"></i> Apenas HTTPS público. Nada entra na IA antes de você clicar em <strong>Publicar na Wiki</strong>.</div>
  <div class="tc-crawler-sources">
  <?php foreach(($knowledgeSources ?? []) as $source): ?>
    <article class="tc-crawler-source"><div class="tc-crawler-source-main"><span class="tc-source-status <?= e($source['status']) ?>"><?= e($source['status']) ?></span><strong><?= e($source['title'] ?: parse_url($source['url'],PHP_URL_HOST)) ?></strong><a href="<?= e($source['url']) ?>" target="_blank" rel="noopener"><?= e($source['url']) ?></a><small><?= $source['last_crawled_at']?'Última análise: '.e(format_date($source['last_crawled_at'],true)):'Ainda não analisada' ?><?= $source['page_title']?' · Wiki: '.e($source['page_title']):'' ?></small><?php if($source['last_error']): ?><em><?= e($source['last_error']) ?></em><?php endif; ?></div><div class="tc-crawler-actions"><button class="btn btn-sm btn-outline-primary tc-source-action" data-id="<?= (int)$source['id'] ?>" data-action="analisar" title="Buscar e analisar agora"><i class="fa-solid fa-magnifying-glass-chart"></i> Analisar</button><button class="btn btn-sm btn-outline-success tc-source-action" data-id="<?= (int)$source['id'] ?>" data-action="publicar" <?= empty($source['extracted_content'])?'disabled':'' ?> title="Inserir ou atualizar na Wiki"><i class="fa-solid fa-book-open"></i> Publicar</button><button class="btn btn-sm btn-outline-danger tc-source-action" data-id="<?= (int)$source['id'] ?>" data-action="excluir" title="Remover fonte e informação publicada"><i class="fa-solid fa-trash"></i></button></div></article>
  <?php endforeach; ?>
  <?php if(empty($knowledgeSources)): ?><div class="tc-crawler-empty">Adicione a primeira página pública que deseja transformar em conhecimento interno.</div><?php endif; ?>
  </div>
</section>
<?php endif; ?>
<div class="row g-3">
  <div class="col-lg-4"><div class="tc-card tc-content-list">
    <?php foreach (($pages ?? []) as $p): ?>
    <button class="tc-content-item" data-page='<?= e(json_encode($p, JSON_UNESCAPED_UNICODE)) ?>'>
      <i class="fa-solid <?= $p['type']==='wiki'?'fa-book':'fa-file-lines' ?>"></i><span><strong><?= e($p['title']) ?></strong><small><?= e($p['tags'] ?: $p['type']) ?><?= $p['lead_name'] ? ' · '.e($p['lead_name']) : '' ?></small></span><?= $p['is_pinned'] ? '<i class="fa-solid fa-thumbtack"></i>' : '' ?>
    </button>
    <?php endforeach; ?>
  </div></div>
  <div class="col-lg-8"><form class="tc-card" id="tcContentForm" data-url="<?= e(url('conteudo/salvar')) ?>" data-upload-base="<?= e(url('conteudo')) ?>" data-lead-search="<?= e(url('leads/buscar-rapido')) ?>">
    <div class="tc-card-body"><input type="hidden" name="id"><input type="hidden" name="type" value="documento">
      <input class="form-control form-control-lg mb-2" name="title" placeholder="Título" required>
      <div class="row g-2 mb-2"><div class="col-md-6"><label class="form-label">Categoria</label><select class="form-select" name="category"><option>Treinamento</option><option>Script de vendas</option><option>Objeções</option><option>Política</option><option>Processo</option><option>Produto</option></select></div><div class="col-md-6"><label class="form-label">Tags</label><input class="form-control" name="tags" placeholder="vendas, treinamento, política"></div></div>
      <div class="row g-2 mb-2"><div class="col-md-6"><label class="form-label">Colaborador responsável (opcional)</label><select class="form-select" name="assigned_to"><option value="">Toda a equipe</option><?php foreach($users as $u): ?><option value="<?= (int)$u['id'] ?>"><?= e($u['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-6 tc-lead-picker" data-url="<?= e(url('leads/buscar-rapido')) ?>"><label class="form-label">Lead relacionado (opcional)</label><input type="hidden" name="lead_id"><input class="form-control tc-lead-search" placeholder="Buscar lead por nome ou contato" autocomplete="off"><div class="tc-lookup-results"></div></div></div>
      <div id="tcQuillEditor"></div>
      <div class="d-flex gap-4 mt-2"><label class="form-check"><input class="form-check-input" type="checkbox" name="is_pinned" value="1"> <span class="form-check-label">Fixar</span></label><label class="form-check"><input class="form-check-input" type="checkbox" name="visibility" value="privado"> <span class="form-check-label">Privado</span></label><label class="form-check"><input class="form-check-input" type="checkbox" name="ai_enabled" value="1" checked> <span class="form-check-label">Disponível para a IA</span></label></div>
      <div class="tc-attachment-box mt-3"><label class="form-label"><i class="fa-solid fa-paperclip"></i> Arquivos anexos</label><input type="file" id="tcContentFiles" class="form-control" multiple accept=".pdf,.txt,.xls,.xlsx,.csv,image/*"><small class="text-muted">PDF, TXT, Excel, CSV ou imagens, até 15 MB por arquivo. Salve o documento antes do primeiro envio.</small><div id="tcAttachmentList" class="mt-2"><?php foreach (($attachments ?? []) as $a): ?><a class="tc-attachment d-none" data-page-id="<?= (int)$a['page_id'] ?>" href="<?= e(UPLOADS_URL.'/workspace/'.$a['stored_name']) ?>" target="_blank"><i class="fa-solid fa-file-arrow-down"></i> <?= e($a['original_name']) ?></a><?php endforeach; ?></div></div>
      <button class="btn btn-tc-primary mt-3">Salvar documento</button>
    </div>
  </form></div>
</div>
<script src="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.js"></script>

<?php elseif ($mode === 'whiteboard'): ?>
<div class="tc-workspace-toolbar"><div><h5>Whiteboard colaborativo</h5><small>Mapeie processos, conecte etapas, compartilhe e vincule ao lead.</small></div><div class="tc-board-toolbar"><button class="btn btn-outline-secondary tc-board-add" data-type="note">+ Nota</button> <button class="btn btn-outline-secondary tc-board-add" data-type="process">+ Processo</button> <button class="btn btn-outline-secondary tc-board-add" data-type="decision">+ Decisão</button><button class="btn btn-outline-primary" id="tcBoardConnect" title="Clique em dois itens para conectá-los"><i class="fa-solid fa-arrow-right-long"></i> Conectar</button> <button class="btn btn-light" id="tcBoardUndo" title="Desfazer"><i class="fa-solid fa-rotate-left"></i></button><button class="btn btn-light" id="tcBoardRedo" title="Refazer"><i class="fa-solid fa-rotate-right"></i></button><button class="btn btn-light" id="tcBoardDelete" title="Excluir item selecionado"><i class="fa-regular fa-trash-can"></i></button><button class="btn btn-light" id="tcBoardZoomOut" title="Diminuir zoom">−</button><span id="tcBoardZoomLabel">100%</span><button class="btn btn-light" id="tcBoardZoomIn" title="Aumentar zoom">+</button><button class="btn btn-outline-danger" id="tcBoardDeleteFlow" title="Excluir whiteboard"><i class="fa-solid fa-trash"></i></button> <button class="btn btn-tc-primary" id="tcBoardSave">Salvar</button></div></div>
<div class="tc-board-meta"><input id="tcBoardTitle" class="form-control" value="Novo fluxo"><div class="tc-lead-picker" data-url="<?= e(url('leads/buscar-rapido')) ?>"><input id="tcBoardLead" type="hidden"><input class="form-control tc-lead-search" placeholder="Buscar lead por nome ou contato"><div class="tc-lookup-results"></div></div><select id="tcBoardExisting" class="form-select"><option value="">Abrir quadro...</option><?php foreach (($boards ?? []) as $b): ?><option value="<?= (int)$b['id'] ?>" data-json="<?= e($b['board_json']) ?>" data-title="<?= e($b['title']) ?>" data-lead="<?= (int)$b['lead_id'] ?>" data-members="<?= e($b['member_ids'] ?? '') ?>"><?= e($b['title']) ?><?= $b['lead_name'] ? ' · '.e($b['lead_name']) : '' ?></option><?php endforeach; ?></select></div>
<div class="tc-board-team mb-2"><span>Compartilhar com:</span><?php foreach ($users as $u): ?><label><input type="checkbox" class="tc-board-member" value="<?= (int)$u['id'] ?>"> <?= e($u['name']) ?></label><?php endforeach; ?></div>
<div id="tcWhiteboard" class="tc-whiteboard" data-url="<?= e(url('whiteboards/salvar')) ?>" data-delete-base="<?= e(url('whiteboards')) ?>" data-csrf="<?= e(Csrf::token()) ?>"><svg class="tc-board-lines" aria-hidden="true"><defs><marker id="tcBoardArrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z"></path></marker></defs></svg><div class="tc-board-grid"></div></div>

<?php elseif ($mode === 'automations'): require APP_PATH . '/views/workspace/_automations.php'; return; ?>
<div class="tc-workspace-toolbar"><div><h5>Automações sem código</h5><small>Crie, teste, pause e execute fluxos integrados aos leads.</small></div><button class="btn btn-tc-primary" id="tcNewFlow">Novo fluxo</button></div>
<div class="row g-3"><div class="col-lg-8">
<?php foreach (($flows ?? []) as $f): $flowData=['id'=>(int)$f['id'],'name'=>$f['name'],'description'=>$f['description']??'','days'=>(int)((json_decode($f['trigger_config'],true)['days']??10)),'actions'=>json_decode($f['actions_json'],true)?:[]]; ?><div class="tc-card mb-2"><div class="tc-card-body d-flex align-items-center gap-3"><i class="fa-solid <?= !empty($f['is_template'])?'fa-copy':'fa-circle-nodes' ?> text-primary fs-4"></i><div class="flex-grow-1"><strong><?= e($f['name']) ?></strong><?= !empty($f['is_template'])?'<span class="badge bg-info ms-1">Modelo</span>':'' ?><div class="text-muted small"><?= e($f['description']??'') ?></div><div class="text-muted small">Lead parado → <?= e(implode(' → ', $flowData['actions'])) ?></div><small class="text-muted">Última execução: <?= e(format_date($f['last_run_at'], true)) ?></small></div><span class="badge bg-<?= $f['active']?'success':'secondary' ?>"><?= $f['active']?'Ativo':'Pausado' ?></span><div class="btn-group"><button class="btn btn-sm btn-outline-info tc-flow-view" data-flow='<?= e(json_encode($flowData,JSON_UNESCAPED_UNICODE)) ?>' title="Ver detalhes"><i class="fa-solid fa-eye"></i></button><button class="btn btn-sm btn-outline-secondary tc-flow-edit" data-flow='<?= e(json_encode($flowData,JSON_UNESCAPED_UNICODE)) ?>' title="<?= !empty($f['is_template'])?'Usar modelo':'Editar' ?>"><i class="fa-solid <?= !empty($f['is_template'])?'fa-copy':'fa-pen' ?>"></i></button><?php if(empty($f['is_template'])): ?><button class="btn btn-sm btn-outline-primary tc-flow-action" data-action="executar" data-id="<?= (int)$f['id'] ?>" title="Executar agora"><i class="fa-solid fa-play"></i></button><button class="btn btn-sm btn-outline-secondary tc-flow-action" data-action="alternar" data-id="<?= (int)$f['id'] ?>" title="Ativar ou pausar"><i class="fa-solid fa-pause"></i></button><button class="btn btn-sm btn-outline-danger tc-flow-action" data-action="excluir" data-id="<?= (int)$f['id'] ?>" title="Excluir"><i class="fa-solid fa-trash"></i></button><?php endif; ?></div></div></div><?php endforeach; ?>
</div><div class="col-lg-4"><form class="tc-card tc-flow-builder" id="tcFlowForm" data-url="<?= e(url('automacoes/salvar')) ?>" data-base="<?= e(url('automacoes')) ?>" data-csrf="<?= e(Csrf::token()) ?>"><div class="tc-card-body"><div class="d-flex justify-content-between align-items-center mb-3"><div><small class="text-primary fw-bold">CONSTRUTOR VISUAL</small><h6 id="tcFlowFormTitle" class="mb-0">Novo fluxo</h6></div><button type="button" class="btn btn-sm btn-outline-primary" data-ai-purpose="assistant" data-ai-prompt="Sugira um fluxo simples para automatizar o acompanhamento comercial dos meus leads."><i class="fa-solid fa-wand-magic-sparkles"></i> Sugerir com IA</button></div><input type="hidden" name="id"><label class="form-label">Nome</label><input name="name" class="form-control mb-2" value="Recuperar lead parado"><label class="form-label">Descrição</label><textarea name="description" class="form-control mb-2" rows="2" placeholder="Objetivo deste fluxo"></textarea><div class="tc-flow-node trigger"><i class="fa-solid fa-bolt"></i><div><small>QUANDO</small><strong>Lead ficar sem interação</strong></div></div><div class="tc-flow-connector"></div><div class="input-group mb-3"><input name="days" type="number" min="1" value="10" class="form-control"><span class="input-group-text">dias</span></div><div class="tc-flow-node action"><i class="fa-solid fa-diagram-project"></i><div><small>ENTÃO</small><strong>Executar ações selecionadas</strong></div></div><div class="tc-flow-actions mt-2"><?php foreach (['Enviar WhatsApp','Criar tarefa','Avisar gestor','Notificar responsável','Aumentar prioridade','Adicionar tag automação','Registrar histórico'] as $a): ?><label class="form-check"><input class="form-check-input" type="checkbox" name="actions[]" value="<?= e($a) ?>" <?= in_array($a,['Enviar WhatsApp','Criar tarefa','Avisar gestor','Aumentar prioridade'],true)?'checked':'' ?>> <span><i class="fa-solid fa-circle-check"></i> <?= e($a) ?></span></label><?php endforeach; ?></div><div id="tcFlowPreview" class="tc-flow-preview"></div><button class="btn btn-tc-primary w-100 mt-3"><i class="fa-solid fa-floppy-disk"></i> Salvar e ativar fluxo</button></div></form></div></div>
<?php endif; ?>
