<?php $s=$copilotSettings; ?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="h3 mb-1">Copiloto de vendas</h1><p class="text-muted mb-0">Orientação consultiva durante a ligação, com relatório separado ao finalizar.</p></div><a class="btn btn-outline-secondary" href="<?= e(url('configuracoes/ligacoes')) ?>">Integrações de ligações</a></div>
<div class="alert alert-info">A ativação é opcional em cada ligação. O vendedor deve confirmar o aviso e informar o cliente sobre a transcrição e análise por IA conforme a política da empresa. O áudio é enviado diretamente ao Gemini em duas trilhas; o CRM recebe os textos. As sugestões e notas são estimativas e precisam de revisão humana.</div>
<form method="post" action="<?= e(url('configuracoes/copiloto')) ?>" autocomplete="off">
<?= Csrf::field() ?>
<div class="card mb-3"><div class="card-body"><h2 class="h5">Ativação e credenciais</h2>
<input type="hidden" name="enabled" value="0"><label class="form-check"><input class="form-check-input" type="checkbox" name="enabled" value="1" <?= $s['enabled']?'checked':'' ?>><span class="form-check-label">Disponibilizar copiloto aos usuários com permissão “Utilizar copiloto de IA”</span></label>
<p class="small text-muted mt-2">Chave <?= $copilotConfigured?'configurada':'não configurada' ?>. Uma chave exclusiva tem preferência; se ausente, será usada a chave Gemini existente. O modelo de análise de ligações já existente não é alterado.</p>
<div class="row g-3"><div class="col-md-6"><label class="form-label" for="copilot-key">Nova chave Gemini (opcional)</label><input id="copilot-key" class="form-control" type="password" name="api_key" maxlength="512" autocomplete="new-password"></div><div class="col-md-6"><label class="form-label" for="copilot-password">Senha atual para substituir a chave</label><input id="copilot-password" class="form-control" type="password" name="current_password" autocomplete="current-password"></div></div>
</div></div>
<div class="card mb-3"><div class="card-body"><h2 class="h5">Modelos e limites</h2><div class="row g-3">
<?php foreach(['live_model'=>'Modelo de transcrição Live','analysis_model'=>'Modelo de análise'] as $key=>$label): ?><div class="col-md-6"><label class="form-label" for="<?= e($key) ?>"><?= e($label) ?></label><input class="form-control" id="<?= e($key) ?>" name="<?= e($key) ?>" value="<?= e($s[$key]) ?>" maxlength="90" required></div><?php endforeach; ?>
<div class="col-md-6"><label class="form-label" for="language">Idioma</label><select class="form-select" id="language" name="language"><?php foreach(['pt-BR'=>'Português brasileiro','en-US'=>'Inglês','es-ES'=>'Espanhol','auto'=>'Automático'] as $k=>$v): ?><option value="<?= e($k) ?>" <?= $s['language']===$k?'selected':'' ?>><?= e($v) ?></option><?php endforeach; ?></select></div>
<div class="col-md-6"><label class="form-label" for="analysis_level">Detalhamento</label><select class="form-select" id="analysis_level" name="analysis_level"><?php foreach(['brief'=>'Breve','balanced'=>'Equilibrado','detailed'=>'Detalhado'] as $k=>$v): ?><option value="<?= e($k) ?>" <?= $s['analysis_level']===$k?'selected':'' ?>><?= e($v) ?></option><?php endforeach; ?></select></div>
<?php foreach(['update_seconds'=>['Intervalo de análise (segundos)',10,120],'max_minutes'=>['Máximo por ligação (minutos)',1,10],'daily_minutes'=>['Minutos reservados por vendedor / dia UTC',1,480],'retention_days'=>['Retenção do relatório (dias)',1,3650]] as $k=>$v): ?><div class="col-md-6"><label class="form-label" for="<?= e($k) ?>"><?= e($v[0]) ?></label><input class="form-control" type="number" id="<?= e($k) ?>" name="<?= e($k) ?>" min="<?= $v[1] ?>" max="<?= $v[2] ?>" value="<?= (int)$s[$k] ?>" required></div><?php endforeach; ?>
</div><p class="small text-muted mt-3">Cada ativação reserva o tempo máximo do dia, inclusive se houver falha ou encerramento antecipado. Tokens são de uso único; não há reconexão automática. A ligação continua normalmente se a IA falhar ou atingir o limite.</p>
<?php foreach(['retain_transcript'=>'Reter transcrição completa junto ao relatório','private_coaching'=>'Manter pontos fortes e melhorias privados para o vendedor'] as $k=>$v): ?><input type="hidden" name="<?= e($k) ?>" value="0"><label class="form-check mb-2"><input class="form-check-input" type="checkbox" name="<?= e($k) ?>" value="1" <?= $s[$k]?'checked':'' ?>><span class="form-check-label"><?= e($v) ?></span></label><?php endforeach; ?>
<p class="small text-muted mb-0">Sem retenção, os trechos são usados temporariamente para gerar o relatório e removidos na finalização. Sessões abandonadas são limpas após o vencimento; a limpeza é executada ao usar ou consultar o copiloto.</p>
</div></div>
<div class="card mb-3"><div class="card-body"><h2 class="h5">Orientações comerciais</h2><p class="small text-muted">Use orientações de venda e evidências observáveis. Não inclua chaves, documentos pessoais ou instruções para executar ações.</p>
<?php foreach(['prompt'=>'Orientação geral','objections'=>'Biblioteca de objeções e respostas','score_criteria'=>'Critérios de pontuação (0–100; desconhecido fica sem nota)','insight_categories'=>'Categorias de interesses, dores e riscos'] as $k=>$v): ?><label class="form-label mt-3" for="<?= e($k) ?>"><?= e($v) ?></label><textarea class="form-control" id="<?= e($k) ?>" name="<?= e($k) ?>" maxlength="8000" rows="3"><?= e($s[$k]) ?></textarea><?php endforeach; ?>
<h3 class="h6 mt-4">Scripts por etapa</h3><div class="row g-3"><?php foreach(['opening'=>'Abertura','discovery'=>'Descoberta','presentation'=>'Apresentação','objections'=>'Objeções','closing'=>'Fechamento','follow_up'=>'Próximo contato'] as $k=>$v): ?><div class="col-md-6"><label class="form-label" for="script-<?= e($k) ?>"><?= e($v) ?></label><textarea class="form-control" id="script-<?= e($k) ?>" name="scripts[<?= e($k) ?>]" maxlength="4000" rows="3"><?= e($s['scripts'][$k]) ?></textarea></div><?php endforeach; ?></div>
</div></div><button class="btn btn-primary" type="submit">Salvar configuração</button></form>
