<?php
declare(strict_types=1);
require_once __DIR__.'/CopilotConfig.php';
final class CopilotInsight {
 private const TEXT=['summary','confidence','suggested_response','next_question','closing_signal','outcome'];
 private const LISTS=['interests','pains','needs','desires','urgencies','restrictions','risks','strengths','improvements','next_steps'];
 private const ENUMS=['interest'=>['unknown','low','medium','high'],'purchase_intent'=>['unknown','very_low','low','medium','high','very_high'],'sentiment'=>['unknown','negative','neutral','positive','mixed'],'priority'=>['unknown','low','medium','high'],'risk'=>['unknown','low','medium','high']];
 public static function schema():array{$p=[];foreach(self::TEXT as $k)$p[$k]=['type'=>'STRING'];foreach(self::LISTS as $k)$p[$k]=['type'=>'ARRAY','items'=>['type'=>'STRING']];foreach(self::ENUMS as $k=>$enum)$p[$k]=['type'=>'STRING','enum'=>$enum];$p['score']=['type'=>'INTEGER','nullable'=>true,'minimum'=>0,'maximum'=>100];$p['conversion_estimate']=['type'=>'INTEGER','nullable'=>true,'minimum'=>0,'maximum'=>100];$p['objections']=['type'=>'ARRAY','items'=>['type'=>'OBJECT','properties'=>['category'=>['type'=>'STRING'],'evidence'=>['type'=>'STRING'],'suggestion'=>['type'=>'STRING']],'required'=>['category','evidence','suggestion']]];return ['type'=>'OBJECT','properties'=>$p,'required'=>array_keys($p)];}
 private static function text($v,int $limit=1500):string {return is_string($v)?mb_substr(trim($v),0,$limit):'';}
 public static function normalize(array $raw):array{$out=[];foreach(self::TEXT as $k)$out[$k]=self::text($raw[$k]??'');foreach(self::LISTS as $k){$out[$k]=[];foreach(array_slice(is_array($raw[$k]??null)?$raw[$k]:[],0,10) as $v){$v=self::text($v,500);if($v!=='')$out[$k][]=$v;}}foreach(self::ENUMS as $k=>$values)$out[$k]=in_array($raw[$k]??null,$values,true)?$raw[$k]:'unknown';$score=$raw['score']??null;$out['score']=is_numeric($score)&&$score>=0&&$score<=100?(int)$score:null;$conversion=$raw['conversion_estimate']??null;$out['conversion_estimate']=is_numeric($conversion)&&$conversion>=0&&$conversion<=100?(int)$conversion:null;$out['confidence']='Estimativa da IA baseada apenas nos trechos disponíveis. '.self::text($raw['confidence']??'',500);$out['objections']=[];foreach(array_slice(is_array($raw['objections']??null)?$raw['objections']:[],0,10) as $v){if(is_array($v))$out['objections'][]=['category'=>self::text($v['category']??'',100),'evidence'=>self::text($v['evidence']??'',500),'suggestion'=>self::text($v['suggestion']??'',700)];}return $out;}
}
