<?php
require_once APP_PATH.'/core/Controller.php';require_once APP_PATH.'/models/CallRecord.php';
final class CallController extends Controller {
 private CallRecord $calls;public function __construct(){$this->calls=new CallRecord();}
 private function allowed(array $c):bool{return Auth::can('calls.view_all')||(Auth::can('calls.view_own')&&(int)($c['assigned_to']??0)===(int)Auth::id());}
 public function index():void{$this->requireLogin();if(!Auth::can('calls.view_all')&&!Auth::can('calls.view_own')){http_response_code(403);return;}$this->view('calls/index',['pageTitle'=>'Ligações','calls'=>$this->calls->recent((int)Auth::id(),Auth::can('calls.view_all'))]);}
 public function show(string $id):void{$this->requireLogin();$c=$this->calls->detail((int)$id);if(!$c){http_response_code(404);return;}if(!$this->allowed($c)){http_response_code(403);return;}$this->view('calls/show',['pageTitle'=>'Análise da ligação','call'=>$c]);}
 public function audio(string $id):void{$this->requireLogin();$c=$this->calls->detail((int)$id);if(!$c||!$this->allowed($c)){http_response_code($c?403:404);return;}$rel=(string)($c['recording_path']??'');$root=realpath(STORAGE_PATH.'/calls');$path=realpath(STORAGE_PATH.'/calls/'.ltrim(str_replace('\\','/',$rel),'/'));if(!$root||!$path||!str_starts_with(strtolower($path),strtolower($root.DIRECTORY_SEPARATOR))||!is_file($path)){http_response_code(404);return;}$size=filesize($path);$start=0;$end=$size-1;if(isset($_SERVER['HTTP_RANGE'])&&preg_match('/bytes=(\d*)-(\d*)/',$_SERVER['HTTP_RANGE'],$m)){$start=$m[1]===''?0:(int)$m[1];$end=$m[2]===''?$end:min($end,(int)$m[2]);if($start>$end){http_response_code(416);return;}http_response_code(206);header("Content-Range: bytes $start-$end/$size");}header('Content-Type: '.((string)($c['recording_mime']?:'audio/mpeg')));header('Accept-Ranges: bytes');header('Cache-Control: private, max-age=300');header('X-Content-Type-Options: nosniff');header('Content-Length: '.($end-$start+1));$h=fopen($path,'rb');fseek($h,$start);$left=$end-$start+1;while($left>0&&!feof($h)){$chunk=fread($h,min(8192,$left));if($chunk===false)break;echo $chunk;$left-=strlen($chunk);}fclose($h);exit;}
}
