<?php
require_once APP_PATH.'/core/Controller.php';require_once APP_PATH.'/models/IntegrationCredential.php';require_once APP_PATH.'/models/AiProviderConfig.php';require_once APP_PATH.'/models/Setting.php';require_once APP_PATH.'/models/User.php';
final class CallAdminController extends Controller {
 private function guard():void{$this->requireLogin();if(!Auth::hasRole(['admin'])||!Auth::can('calls.manage')){http_response_code(403);exit;}}
 private function config():IntegrationConfig{return new IntegrationConfig(new IntegrationCredential(),SecretVault::fromFile(ROOT_PATH.'/config/integration.key'),IntegrationConfig::legacyEnvironment(ROOT_PATH.'/ligacao/.env'));}
 public function index():void{$this->guard();$c=$this->config();$this->view('settings/calls',['pageTitle'=>'Integrações de Ligações','profiles'=>(new AiProviderConfig())->profiles(),'settings'=>(new Setting())->allAsMap(),'configured'=>['api4com'=>$c->isConfigured('api4com','token'),'gemini'=>$c->isConfigured('gemini','api_key'),'openrouter'=>$c->isConfigured('openrouter','api_key')]]);}
 public function save():void{$this->guard();Csrf::verifyRequest();$u=(new User())->find((int)Auth::id());if(!$u||!password_verify((string)$this->input('current_password',''),$u['password'])){flash('error','Senha atual inválida.');$this->redirect('configuracoes/ligacoes');return;}$p=(string)$this->input('provider','');if(!in_array($p,['api4com','gemini','openrouter'],true)){http_response_code(422);return;}$base=filter_var((string)$this->input('base_url',''),FILTER_VALIDATE_URL);if(!$base||parse_url($base,PHP_URL_SCHEME)!=='https'){flash('error','Informe uma URL HTTPS válida.');$this->redirect('configuracoes/ligacoes');return;}$c=$this->config();$c->setPublic($p,'base_url',rtrim($base,'/'),(int)Auth::id());$c->setSecret($p,$p==='api4com'?'token':'api_key',trim((string)$this->input('secret','')),(int)Auth::id());if($p!=='api4com')(new AiProviderConfig())->saveProfile($p,rtrim($base,'/'),trim((string)$this->input('model','')),max(1048576,min(104857600,(int)$this->input('max_audio_bytes',14680064))),true,$this->input('is_active','')==='1');else(new Setting())->setMany(['calls_audio_retention_days'=>(string)max(0,min(3650,(int)$this->input('retention_days',365)))]);log_activity('calls_integration_updated','Configuração da integração '.$p.' atualizada sem registrar credenciais.');flash('success','Integração salva com segurança.');$this->redirect('configuracoes/ligacoes');}
 public function test(string $provider):void{$this->guard();Csrf::verifyRequest();if(!in_array($provider,['api4com','gemini','openrouter'],true)){http_response_code(422);return;}$c=$this->config();try{$base=rtrim((string)$c->get($provider,'base_url',$provider==='api4com'?'https://api.api4com.com/api/v1':($provider==='gemini'?'https://generativelanguage.googleapis.com/v1beta':'https://openrouter.ai/api/v1')),'/');$url=$provider==='api4com'?$base.'/calls?page=1&filter='.rawurlencode('{"limit":1}'):$base.'/models';$headers=['Accept: application/json'];if($provider==='api4com')$headers[]='Authorization: '.$c->get($provider,'token','');elseif($provider==='gemini')$url.='?key='.rawurlencode((string)$c->get($provider,'api_key',''));else$headers[]='Authorization: Bearer '.$c->get($provider,'api_key','');$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>20,CURLOPT_HTTPHEADER=>$headers]);curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);if($code<200||$code>=300)throw new RuntimeException('CONNECTION_FAILED');if($provider!=='api4com')(new AiProviderConfig())->markTest($provider,true);flash('success','Conexão com '.$provider.' validada.');}catch(Throwable$e){if($provider!=='api4com')(new AiProviderConfig())->markTest($provider,false,'CONNECTION_FAILED');flash('error','Não foi possível validar a integração. Confira URL, token e modelo.');}$this->redirect('configuracoes/ligacoes');}
}
