<?php
require_once APP_PATH.'/core/Model.php';
final class CallRecord extends Model {
 protected string $table='call_records';
 private string $select="SELECT c.*,l.name lead_name,l.assigned_to,u.name agent_name,a.summary,a.transcript,a.sentiment,a.lead_temperature,a.sales_stage,a.overall_score,a.payload,a.provider analysis_provider,a.provider_model,a.analyzed_at FROM call_records c LEFT JOIN leads l ON l.id=c.lead_id LEFT JOIN users u ON u.id=c.user_id LEFT JOIN call_analyses a ON a.call_id=c.id";
 public function recent(int $uid,bool $all,int $limit=100):array{$sql=$this->select." WHERE c.outcome<>'voicemail'".($all?'':' AND l.assigned_to=:uid').' ORDER BY c.started_at DESC LIMIT '.max(1,min(200,$limit));$s=$this->db->prepare($sql);$s->execute($all?[]:[':uid'=>$uid]);return $s->fetchAll();}
 public function search(int $uid,bool $all,array $filters=[],int $page=1,int $perPage=20):array{$status=(string)($filters['status']??'');$where=[$status==='voicemail'?"c.outcome='voicemail'":"c.outcome<>'voicemail'"];$params=[];if(!$all){$where[]='l.assigned_to=:uid';$params[':uid']=$uid;}$number=preg_replace('/\D+/','',(string)($filters['number']??''))?:'';if($number!==''){$where[]='c.normalized_phone LIKE :number';$params[':number']='%'.substr($number,0,20).'%';}if($status==='analyzed')$where[]="c.analysis_status='completed'";elseif($status==='pending')$where[]="c.analysis_status IN('pending','processing')";elseif($status==='failed')$where[]="c.analysis_status='failed'";elseif($status==='unmatched')$where[]='c.lead_id IS NULL';elseif($status==='unanswered')$where[]="c.outcome IN('no_answer','invalid_number','short_or_silent')";$clause=implode(' AND ',$where);$count=$this->db->prepare('SELECT COUNT(*) FROM call_records c LEFT JOIN leads l ON l.id=c.lead_id WHERE '.$clause);$count->execute($params);$total=(int)$count->fetchColumn();$perPage=max(10,min(100,$perPage));$pages=max(1,(int)ceil($total/$perPage));$page=max(1,min($pages,$page));$query=$this->db->prepare($this->select.' WHERE '.$clause.' ORDER BY c.started_at DESC LIMIT '.$perPage.' OFFSET '.(($page-1)*$perPage));$query->execute($params);return['items'=>$query->fetchAll(),'total'=>$total,'page'=>$page,'pages'=>$pages];}
 public function detail(int $id):?array{$s=$this->db->prepare($this->select.' WHERE c.id=:id LIMIT 1');$s->execute([':id'=>$id]);$r=$s->fetch();if(!$r)return null;$r['analysis_payload']=json_decode((string)($r['payload']??''),true)?:[];return $r;}
 public function syncState():array{try{$row=$this->db->query("SELECT * FROM call_sync_state WHERE provider='api4com' LIMIT 1")->fetch();if(!$row)return[];$row['last_counts']=json_decode((string)($row['last_counts']??''),true)?:[];return$row;}catch(Throwable){return[];}}
 public function forLead(int $id):array{$s=$this->db->prepare($this->select." WHERE c.lead_id=:id AND c.outcome<>'voicemail' ORDER BY c.started_at DESC");$s->execute([':id'=>$id]);return $s->fetchAll();}
}
