<?php
/** Central de relatórios: visão executiva, funil, equipe, operação e base. */
$queryFilters = array_filter(
    $filters,
    static fn($value, $key) => $value !== '' && $value !== null && !($key === 'period' && $value === 'all'),
    ARRAY_FILTER_USE_BOTH
);
$queryString = http_build_query($queryFilters);
$jsonFlags = JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE;
$taskLabels = [
    'pendente' => 'Pendente', 'em_andamento' => 'Em andamento', 'aguardando' => 'Aguardando',
    'concluida' => 'Concluída', 'cancelada' => 'Cancelada',
];
$chartPayload = [
    'status' => ['labels' => array_map('status_label', array_keys($statusChart)), 'data' => array_values($statusChart)],
    'source' => ['labels' => array_map('source_label', array_keys($sourceChart)), 'data' => array_values($sourceChart)],
    'state' => ['labels' => array_keys($stateChart), 'data' => array_values($stateChart)],
    'loss' => ['labels' => array_keys($lossChart), 'data' => array_values($lossChart)],
    'leads' => ['labels' => array_map(static fn($row) => format_date($row['day']), $leadSeries), 'data' => array_map(static fn($row) => $row['total'], $leadSeries)],
    'revenue' => ['labels' => array_map(static fn($row) => format_date($row['day']), $revenueSeries), 'data' => array_map(static fn($row) => $row['total'], $revenueSeries)],
    'team' => ['labels' => array_map(static fn($row) => $row['name'], array_slice($performance, 0, 10)), 'data' => array_map(static fn($row) => $row['conversion_rate'], array_slice($performance, 0, 10))],
    'tasks' => ['labels' => array_map(static fn($key) => $taskLabels[$key] ?? ucfirst(str_replace('_', ' ', $key)), array_keys($taskSummary['by_status'] ?? [])), 'data' => array_values($taskSummary['by_status'] ?? [])],
];
?>

<div id="tcReportsApp"
     data-charts="<?= e((string) json_encode($chartPayload, $jsonFlags)) ?>"
     data-ai-url="<?= e(url('relatorios/analisar-ia')) ?>"
     data-csrf="<?= e(Csrf::token()) ?>">
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-3">
        <div>
            <h4 class="mb-1">Central de relatórios</h4>
            <p class="text-muted mb-0">Métricas de captação, conversão, receita, equipe e operação em um só lugar.</p>
        </div>
        <span class="badge text-bg-light border px-3 py-2"><i class="fa-regular fa-calendar me-1"></i> <?= e($periodLabel) ?></span>
    </div>

    <div class="tc-card mb-3">
        <div class="tc-card-body">
            <form method="GET" action="<?= e(url('relatorios')) ?>" id="tcReportFilters" class="row g-2 align-items-end">
                <div class="col-sm-6 col-lg-2"><label class="form-label">Período</label><select name="period" id="tcReportPeriod" class="form-select"><option value="all" <?= $filters['period'] === 'all' ? 'selected' : '' ?>>Todo o histórico</option><option value="today" <?= $filters['period'] === 'today' ? 'selected' : '' ?>>Hoje</option><option value="7d" <?= $filters['period'] === '7d' ? 'selected' : '' ?>>Últimos 7 dias</option><option value="30d" <?= $filters['period'] === '30d' ? 'selected' : '' ?>>Últimos 30 dias</option><option value="month" <?= $filters['period'] === 'month' ? 'selected' : '' ?>>Este mês</option><option value="quarter" <?= $filters['period'] === 'quarter' ? 'selected' : '' ?>>Este trimestre</option><option value="custom" <?= $filters['period'] === 'custom' ? 'selected' : '' ?>>Personalizado</option></select></div>
                <div class="col-6 col-lg-2"><label class="form-label">Cadastro: de</label><input type="date" name="date_from" class="form-control" value="<?= e($filters['date_from']) ?>"></div>
                <div class="col-6 col-lg-2"><label class="form-label">Cadastro: até</label><input type="date" name="date_to" class="form-control" value="<?= e($filters['date_to']) ?>"></div>
                <div class="col-sm-6 col-lg-2"><label class="form-label">Responsável</label><select name="assigned_to" class="form-select"><option value="">Todos</option><?php foreach ($users as $u): ?><option value="<?= (int) $u['id'] ?>" <?= $filters['assigned_to'] === (string) $u['id'] ? 'selected' : '' ?>><?= e($u['name']) ?></option><?php endforeach; ?></select></div>
                <div class="col-sm-6 col-lg-2"><label class="form-label">Origem</label><select name="source" class="form-select"><option value="">Todas</option><?php foreach (['facebook','instagram','google','indicacao','site','landing_page','organico','cadastro_manual','whatsapp','importacao_csv','api','webhook','outros'] as $source): ?><option value="<?= e($source) ?>" <?= $filters['source'] === $source ? 'selected' : '' ?>><?= e(source_label($source)) ?></option><?php endforeach; ?></select></div>
                <div class="col-sm-6 col-lg-2"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">Todos</option><?php foreach (['novo','primeiro_contato','tentando_contato','em_negociacao','documentacao','aguardando_cliente','aguardando_aprovacao','aprovado','fechado','perdido','sem_interesse','sem_entrada','numero_invalido','nao_responde','bloqueou','duplicado'] as $status): ?><option value="<?= e($status) ?>" <?= $filters['status'] === $status ? 'selected' : '' ?>><?= e(status_label($status)) ?></option><?php endforeach; ?></select></div>
                <div class="col-sm-6 col-lg-2"><label class="form-label">Interesse</label><select name="interest" class="form-select"><option value="">Todos</option><?php foreach (['imovel','veiculo','caminhao','moto','maquinario','agronegocio','construcao','capital_giro','investimento','quitacao','outros'] as $interest): ?><option value="<?= e($interest) ?>" <?= $filters['interest'] === $interest ? 'selected' : '' ?>><?= e(interest_label($interest)) ?></option><?php endforeach; ?></select></div>
                <div class="col-sm-6 col-lg-2"><label class="form-label">Estado</label><select name="state" class="form-select"><option value="">Todos</option><?php foreach ($states as $uf => $name): ?><option value="<?= e($uf) ?>" <?= $filters['state'] === $uf ? 'selected' : '' ?>><?= e($uf) ?></option><?php endforeach; ?></select></div>
                <div class="col-12 d-flex flex-wrap gap-2 pt-1"><button type="submit" class="btn btn-tc-primary"><i class="fa-solid fa-filter me-1"></i> Atualizar relatórios</button><a href="<?= e(url('relatorios')) ?>" class="btn btn-outline-secondary">Limpar filtros</a><?php if ($hasFilters): ?><small class="text-muted align-self-center">O recorte afeta os relatórios comerciais e a exportação.</small><?php endif; ?></div>
            </form>
        </div>
    </div>

    <nav class="nav nav-pills tc-report-nav mb-3" aria-label="Tipos de relatório">
        <a class="nav-link active" href="#relatorio-executivo"><i class="fa-solid fa-chart-pie me-1"></i> Visão executiva</a><a class="nav-link" href="#relatorio-funil"><i class="fa-solid fa-filter-circle-dollar me-1"></i> Funil e conversão</a><a class="nav-link" href="#relatorio-equipe"><i class="fa-solid fa-users me-1"></i> Equipe e receita</a><a class="nav-link" href="#relatorio-operacao"><i class="fa-solid fa-headset me-1"></i> Operação</a><a class="nav-link" href="#relatorio-base"><i class="fa-solid fa-table-list me-1"></i> Base detalhada</a>
    </nav>

    <section id="relatorio-executivo" class="tc-report-section mb-4">
        <div class="d-flex align-items-center justify-content-between gap-2 mb-2"><div><h5 class="mb-0">Visão executiva</h5><small class="text-muted">Leads cadastrados no recorte selecionado.</small></div><?php if ($aiReportAvailable): ?><button type="button" class="btn btn-outline-primary btn-sm" id="tcReportAiOpen"><i class="fa-solid fa-sparkles me-1"></i> Analisar com IA</button><?php else: ?><span class="small text-muted"><i class="fa-solid fa-sparkles me-1"></i> Análise por IA opcional — não configurada</span><?php endif; ?></div>
        <div class="row g-3 mb-3">
            <div class="col-6 col-lg-3"><div class="tc-kpi-card h-100"><div class="tc-kpi-icon bg-primary-subtle text-primary"><i class="fa-solid fa-user-group"></i></div><div><div class="tc-kpi-value"><?= (int) $kpis['total'] ?></div><div class="tc-kpi-label">Leads no recorte</div></div></div></div>
            <div class="col-6 col-lg-3"><div class="tc-kpi-card h-100"><div class="tc-kpi-icon bg-info-subtle text-info"><i class="fa-solid fa-phone"></i></div><div><div class="tc-kpi-value"><?= number_format($kpis['contact_rate'], 1, ',', '.') ?>%</div><div class="tc-kpi-label">Taxa de contato</div></div></div></div>
            <div class="col-6 col-lg-3"><div class="tc-kpi-card h-100"><div class="tc-kpi-icon bg-success-subtle text-success"><i class="fa-solid fa-bullseye"></i></div><div><div class="tc-kpi-value"><?= number_format($kpis['conversion_rate'], 1, ',', '.') ?>%</div><div class="tc-kpi-label">Conversão (<?= (int) $kpis['closed'] ?> fechados)</div></div></div></div>
            <div class="col-6 col-lg-3"><div class="tc-kpi-card h-100"><div class="tc-kpi-icon bg-warning-subtle text-warning"><i class="fa-solid fa-sack-dollar"></i></div><div><div class="tc-kpi-value tc-report-money"><?= e(format_money($kpis['revenue'])) ?></div><div class="tc-kpi-label">Receita realizada</div></div></div></div>
        </div>
        <?php if ($aiReportAvailable): ?><div id="tcReportAiPanel" class="tc-report-ai tc-card mb-3" hidden><div class="tc-card-header d-flex justify-content-between align-items-center"><span><i class="fa-solid fa-sparkles me-1"></i> Leitura assistida por IA</span><button type="button" class="btn-close" id="tcReportAiClose" aria-label="Fechar"></button></div><div class="tc-card-body"><p class="small text-muted">A IA recebe somente indicadores agregados deste painel — sem nomes, contatos ou mensagens dos leads.</p><form id="tcReportAiForm" class="row g-2 align-items-end"><div class="col-md"><label class="form-label">Pergunta opcional</label><input type="text" class="form-control" name="question" maxlength="1000" placeholder="Ex.: Onde devemos concentrar a equipe nesta semana?"></div><div class="col-md-auto"><button type="submit" class="btn btn-primary" id="tcReportAiSubmit"><i class="fa-solid fa-wand-magic-sparkles me-1"></i> Gerar análise</button></div></form><div id="tcReportAiResult" class="tc-report-ai-result mt-3" aria-live="polite" hidden></div></div></div><?php endif; ?>
        <div class="row g-3"><div class="col-xl-7"><div class="tc-card h-100"><div class="tc-card-header">Entradas de leads por dia <small class="text-muted fw-normal">(até 90 dias)</small></div><div class="tc-card-body"><div class="tc-chart-wrap"><canvas id="chartReportLeads"></canvas></div></div></div></div><div class="col-xl-5"><div class="tc-card h-100"><div class="tc-card-header">Receita realizada por fechamento</div><div class="tc-card-body"><div class="tc-chart-wrap"><canvas id="chartReportRevenue"></canvas></div><small class="text-muted">Considera o valor efetivo informado nos leads fechados do recorte.</small></div></div></div></div>
        <div class="tc-insight-card mt-3"><i class="fa-solid fa-circle-info"></i><span><strong>Leitura rápida:</strong> <?= (int) $kpis['active'] ?> em andamento, <?= (int) $kpis['lost'] ?> perdidos, <?= (int) $kpis['hot'] ?> lead(s) quente(s) e <?= (int) $kpis['unassigned'] ?> sem responsável. Ticket médio realizado: <strong><?= e(format_money($kpis['average_ticket'])) ?></strong>.</span></div>
    </section>

    <section id="relatorio-funil" class="tc-report-section mb-4">
        <div class="mb-2"><h5 class="mb-0">Funil, captação e qualidade</h5><small class="text-muted">Entenda em que etapa os leads estão e quais origens convertem melhor.</small></div>
        <div class="row g-3 mb-3"><div class="col-lg-6"><div class="tc-card h-100"><div class="tc-card-header">Leads por status</div><div class="tc-card-body"><div class="tc-chart-wrap"><canvas id="chartReportStatus"></canvas></div></div></div></div><div class="col-lg-6"><div class="tc-card h-100"><div class="tc-card-header">Leads por origem</div><div class="tc-card-body"><div class="tc-chart-wrap"><canvas id="chartReportSource"></canvas></div></div></div></div></div>
        <div class="row g-3"><div class="col-xl-8"><div class="tc-card h-100"><div class="tc-card-header">Conversão e receita por origem</div><div class="table-responsive"><table class="table tc-table mb-0"><thead><tr><th>Origem</th><th class="text-center">Leads</th><th class="text-center">Fechados</th><th class="text-center">Perdidos</th><th class="text-center">Conversão</th><th class="text-end">Receita</th></tr></thead><tbody><?php if (empty($sourcePerformance)): ?><tr><td colspan="6" class="text-center text-muted py-4">Sem dados no recorte.</td></tr><?php endif; ?><?php foreach ($sourcePerformance as $source => $row): ?><tr><td class="fw-semibold"><?= e(source_label($source)) ?></td><td class="text-center"><?= (int) $row['total'] ?></td><td class="text-center text-success"><?= (int) $row['fechado'] ?></td><td class="text-center text-danger"><?= (int) $row['perdido'] ?></td><td class="text-center"><span class="badge bg-<?= $row['conversion_rate'] >= 20 ? 'success' : ($row['conversion_rate'] >= 5 ? 'warning' : 'secondary') ?>"><?= number_format($row['conversion_rate'], 1, ',', '.') ?>%</span></td><td class="text-end"><?= e(format_money($row['revenue'])) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div><div class="col-xl-4"><div class="tc-card h-100"><div class="tc-card-header">Motivos de perda</div><div class="tc-card-body"><?php if (empty($lossChart)): ?><div class="text-muted text-center py-5">Sem perdas no recorte.</div><?php else: ?><div class="tc-chart-wrap"><canvas id="chartReportLoss"></canvas></div><?php endif; ?></div></div></div></div>
        <div class="row g-3 mt-0"><div class="col-xl-6"><div class="tc-card h-100"><div class="tc-card-header">Distribuição geográfica</div><div class="tc-card-body"><?php if (empty($stateChart)): ?><div class="text-muted text-center py-5">Sem UF informada no recorte.</div><?php else: ?><div class="tc-chart-wrap"><canvas id="chartReportState"></canvas></div><?php endif; ?></div></div></div></div>
    </section>

    <section id="relatorio-equipe" class="tc-report-section mb-4">
        <div class="mb-2"><h5 class="mb-0">Desempenho da equipe e receita</h5><small class="text-muted">Distribuição comercial pelo responsável atual do lead.</small></div>
        <div class="row g-3 mb-3"><div class="col-lg-5"><div class="tc-card h-100"><div class="tc-card-header">Conversão por responsável</div><div class="tc-card-body"><?php if (empty($performance)): ?><div class="text-muted text-center py-5">Sem responsáveis no recorte.</div><?php else: ?><div class="tc-chart-wrap"><canvas id="chartReportTeam"></canvas></div><?php endif; ?></div></div></div><div class="col-lg-7"><div class="tc-card h-100"><div class="tc-card-header">Indicadores de valor</div><div class="tc-card-body"><div class="row text-center g-3"><div class="col-4"><div class="tc-kpi-value"><?= e(format_money($kpis['revenue'])) ?></div><div class="tc-kpi-label">Receita realizada</div></div><div class="col-4"><div class="tc-kpi-value"><?= e(format_money($kpis['average_ticket'])) ?></div><div class="tc-kpi-label">Ticket médio</div></div><div class="col-4"><div class="tc-kpi-value"><?= (int) $kpis['closed'] ?></div><div class="tc-kpi-label">Fechamentos</div></div></div><hr><p class="small text-muted mb-0">A receita utiliza exclusivamente <em>Valor realizado</em> preenchido no fechamento. Valores desejados não são tratados como venda.</p></div></div></div></div>
        <div class="tc-card"><div class="tc-card-header">Detalhamento por responsável</div><div class="table-responsive"><table class="table tc-table mb-0"><thead><tr><th>Responsável</th><th class="text-center">Leads</th><th class="text-center">Contatados</th><th class="text-center">Fechados</th><th class="text-center">Perdidos</th><th class="text-center">Conversão</th><th class="text-center">Score médio</th><th class="text-end">Receita</th></tr></thead><tbody><?php if (empty($performance)): ?><tr><td colspan="8" class="text-center text-muted py-4">Nenhum lead no recorte.</td></tr><?php endif; ?><?php foreach ($performance as $row): ?><tr><td class="fw-semibold"><?= e($row['name']) ?></td><td class="text-center"><?= (int) $row['total'] ?></td><td class="text-center"><?= (int) $row['contacted'] ?> <small class="text-muted">(<?= number_format($row['contact_rate'], 0, ',', '.') ?>%)</small></td><td class="text-center text-success"><?= (int) $row['fechado'] ?></td><td class="text-center text-danger"><?= (int) $row['perdido'] ?></td><td class="text-center"><span class="badge bg-<?= $row['conversion_rate'] >= 20 ? 'success' : ($row['conversion_rate'] >= 5 ? 'warning' : 'secondary') ?>"><?= number_format($row['conversion_rate'], 1, ',', '.') ?>%</span></td><td class="text-center"><span class="badge bg-<?= score_badge_class($row['avg_score']) ?>"><?= number_format($row['avg_score'], 1, ',', '.') ?></span></td><td class="text-end"><?= e(format_money($row['revenue'])) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
    </section>

    <section id="relatorio-operacao" class="tc-report-section mb-4">
        <div class="mb-2"><h5 class="mb-0">Operação de atendimento</h5><small class="text-muted">Resumo geral de tarefas e WhatsApp, independente do filtro comercial acima.</small></div>
        <div class="row g-3"><div class="col-lg-6"><div class="tc-card h-100"><div class="tc-card-header"><i class="fa-solid fa-list-check me-1"></i> Tarefas</div><div class="tc-card-body"><?php if (!$taskSummary): ?><div class="text-muted text-center py-4">Módulo de tarefas ainda não disponível.</div><?php else: ?><div class="row text-center g-2 mb-3"><div class="col-3"><div class="tc-kpi-value"><?= (int) $taskSummary['total'] ?></div><div class="tc-kpi-label">Total</div></div><div class="col-3"><div class="tc-kpi-value"><?= (int) $taskSummary['open'] ?></div><div class="tc-kpi-label">Abertas</div></div><div class="col-3"><div class="tc-kpi-value text-success"><?= (int) $taskSummary['completed'] ?></div><div class="tc-kpi-label">Concluídas</div></div><div class="col-3"><div class="tc-kpi-value text-danger"><?= (int) $taskSummary['overdue'] ?></div><div class="tc-kpi-label">Atrasadas</div></div></div><div class="tc-chart-wrap" style="height:190px"><canvas id="chartReportTasks"></canvas></div><a href="<?= e(url('tarefas')) ?>" class="btn btn-outline-primary btn-sm w-100 mt-2">Abrir tarefas</a><?php endif; ?></div></div></div><div class="col-lg-6"><div class="tc-card h-100"><div class="tc-card-header"><i class="fa-brands fa-whatsapp me-1"></i> Atendimento WhatsApp</div><div class="tc-card-body"><?php if (!$whatsappSummary): ?><div class="text-muted text-center py-4">Atendimento WhatsApp ainda não configurado.</div><?php else: ?><div class="row g-2 text-center"><div class="col-6"><div class="tc-kpi-value"><?= (int) $whatsappSummary['conversations'] ?></div><div class="tc-kpi-label">Conversas</div></div><div class="col-6"><div class="tc-kpi-value"><?= (int) $whatsappSummary['unread'] ?></div><div class="tc-kpi-label">Não lidas</div></div><div class="col-6"><div class="tc-kpi-value"><?= (int) $whatsappSummary['received_30d'] ?></div><div class="tc-kpi-label">Recebidas (30d)</div></div><div class="col-6"><div class="tc-kpi-value"><?= (int) $whatsappSummary['sent_30d'] ?></div><div class="tc-kpi-label">Enviadas (30d)</div></div></div><div class="small text-muted text-center mt-3"><?= (int) $whatsappSummary['linked'] ?> vinculada(s) a lead · <?= (int) $whatsappSummary['unassigned'] ?> sem responsável</div><a href="<?= e(url('atendimento-whatsapp')) ?>" class="btn btn-outline-success btn-sm w-100 mt-2">Abrir Atendimento WhatsApp</a><?php endif; ?></div></div></div></div>
    </section>

    <section id="relatorio-base" class="tc-report-section mb-4">
        <div class="d-flex flex-wrap justify-content-between align-items-center mb-2 gap-2"><div><h5 class="mb-0">Base detalhada de leads</h5><small class="text-muted"><?= (int) $previewCount ?> lead(s) no recorte; prévia limitada a 50 linhas.</small></div><?php if (Auth::can('leads.export')): ?><div class="d-flex flex-wrap gap-2"><a href="<?= e(url('relatorios/exportar-csv?' . $queryString)) ?>" class="btn btn-outline-secondary btn-sm"><i class="fa-solid fa-file-csv me-1"></i> CSV</a><a href="<?= e(url('relatorios/exportar-excel?' . $queryString)) ?>" class="btn btn-outline-secondary btn-sm"><i class="fa-solid fa-file-excel me-1"></i> Excel</a><a href="<?= e(url('relatorios/imprimir?' . $queryString)) ?>" target="_blank" rel="noopener" class="btn btn-outline-secondary btn-sm"><i class="fa-solid fa-file-pdf me-1"></i> PDF</a><a href="<?= e(url('relatorios/personalizar')) ?>" class="btn btn-tc-primary btn-sm"><i class="fa-solid fa-palette me-1"></i> Personalizar</a></div><?php endif; ?></div>
        <div class="tc-table-card"><div class="table-responsive"><table class="table tc-table"><thead><tr><th>Nome</th><th>Telefone</th><th>Cidade/UF</th><th>Origem</th><th>Status</th><th>Responsável</th><th>Score</th><th>Valor realizado</th><th>Cadastro</th></tr></thead><tbody><?php if (empty($preview)): ?><tr><td colspan="9" class="text-center text-muted py-4">Nenhum lead encontrado para os filtros selecionados.</td></tr><?php endif; ?><?php foreach ($preview as $lead): ?><tr><td><?= e($lead['name'] ?: 'Sem nome') ?></td><td><?= e(format_phone($lead['whatsapp'] ?: $lead['phone'])) ?></td><td><?= e($lead['city'] ? $lead['city'] . '/' . $lead['state'] : '-') ?></td><td><?= e(source_label($lead['source'])) ?></td><td><span class="badge bg-<?= e(status_color($lead['status'])) ?>"><?= e(status_label($lead['status'])) ?></span></td><td><?= e($lead['assigned_name'] ?: '-') ?></td><td><?= (int) $lead['lead_score'] ?></td><td><?= e(format_money($lead['closed_value'] ?? null)) ?></td><td><?= e(format_date($lead['created_at'])) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
        <div class="tc-insight-card mt-3"><i class="fa-solid fa-circle-info"></i><span>O PDF abre uma página formatada para impressão: use “Salvar como PDF” no navegador. As colunas dos arquivos exportados podem ser ajustadas em <strong>Personalizar</strong>.</span></div>
    </section>
</div>

<?php $pageScripts = '<script src="' . e(asset('js/reports.js')) . '"></script>'; ?>
